name: data_structures_final_project
description: A web server built using pure dart.
# version: 1.0.0
# homepage: https://www.github.com/ali-alizadeh/data_structures_final_project
# author: Ali Alizadeh <alizadeh.ali.e@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
